/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

/**
 *
 * @author aariasg
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpleado = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setTitle("Sistema Gestion Metal Mecanica");

        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imag/Female.gif"))); // NOI18N
        btnEmpleado.setText("Empleado");

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imag/Boss.gif"))); // NOI18N
        btnCliente.setText("Cliente");

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imag/Clipboard.gif"))); // NOI18N
        btnInventario.setText("Inventario");

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imag/Notes.gif"))); // NOI18N
        btnPedido.setText("Pedido");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imag/Exit.gif"))); // NOI18N
        btnSalir.setText("Salir");

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imag/Info.gif"))); // NOI18N
        btnInfo.setText("Informacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnInfo)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventario)
                    .addComponent(btnPedido))
                .addGap(89, 89, 89)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInfo)
                .addGap(32, 32, 32))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCliente;
    public javax.swing.JButton btnEmpleado;
    public javax.swing.JButton btnInfo;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnPedido;
    public javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables
}
